# Generated by Django 3.2.23 on 2023-12-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_date', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dew', models.FloatField()),
                ('slp', models.FloatField()),
                ('tmp', models.FloatField()),
                ('vis', models.FloatField()),
                ('wnd', models.FloatField()),
            ],
        ),
    ]
